quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),  
    path('detail/<int:quote_id>', views.detail, name='detail'),  
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path('author/', views.author, name='author'),   
    path('author_detail/<int:author_id>', views.author_detail, name='author_detail'),          
]

quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes/quoteapp/models.py
from django.db import models

# Create your models here.
# class Quote(Document):
#     tags = ListField()
#     author = ReferenceField(Author)
#     quote = StringField()

# class Author(Document):
#     fullname = StringField()
#     born_date = StringField()
#     born_location = StringField()
#     description = StringField()

MAX_LENGTH = 50 # max length of the string fields
MAX_LENGTH_DESCRIPTION = 2000

class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_DESCRIPTION, null=False, unique=True)
    def __str__(self):
        return f"{self.name}"    

class Author(models.Model):
    fullname = models.CharField(max_length=MAX_LENGTH_DESCRIPTION,null=False)
    born_date = models.CharField(max_length=MAX_LENGTH_DESCRIPTION,null=False)
    born_location = models.CharField(max_length=MAX_LENGTH_DESCRIPTION,null=False)
    description = models.CharField(max_length=MAX_LENGTH_DESCRIPTION, null= False)
    def __str__(self):
        return f"{self.fullname}"

class Quote(models.Model):
    quote = models.CharField(max_length=MAX_LENGTH_DESCRIPTION, null=False)
    author = models.CharField(max_length=MAX_LENGTH_DESCRIPTION, null=False) #models.ForeignKey(Author, on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return f"{self.name}"

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Quote,Tag, Author
from .models import MAX_LENGTH_DESCRIPTION,MAX_LENGTH

class QuoteForm(ModelForm):

    quote = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())
    author = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote','author']
        exclude = ['tags']

class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class AuthorForm(ModelForm):
    fullname = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())
    born_date = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())
    born_location = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())
    description = CharField(min_length=5, max_length=MAX_LENGTH_DESCRIPTION, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ["fullname","born_date","born_location","description"]

quotes/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import QuoteForm,TagForm,AuthorForm
from .models import Quote,Tag,Author


# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    authors = Author.objects.all()

    return render(request, 'quoteapp/index.html', {"quotes": quotes,"authors":authors})

def quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': QuoteForm()})

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})

def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail.html', {"quote": quote})

@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quoteapp:main')

@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

def author_detail(request,author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quoteapp/author_detail.html', {"author": author})

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author Name:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>

    <div style="padding: 10px">
        <label> Date of Birth:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>

    <div style="padding: 10px">
        <label> Place of Birht:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>

    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>


    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/author_detail.html
{% extends "quoteapp/base.html" %}
{% load extract_tags %}

{% block content %}

<h1>{{author.fullname}}</h1>
<p>Born Date: <b>{{author.born_date}}</b></p>
<p>Born Location: <b>{{author.born_location}}</b></p>
<p>Description: <b>{{author.description}}</b></p>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quote information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %}
{% load extract_tags %}

{% block content %}

<h1>{{quote.quote}}</h1>
<p>Author: <b>{{quote.author}}</b></p>
<p>Tags: <small>
        {{ quote.tags|tags }}
    </small></p>
{% endblock %}

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quoteapp:quote' %}" role="button">Add Quote</a></li>
                <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
                <li><a href="{% url 'quoteapp:author' %}" role="button">Add Author</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>

            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}

        </nav>

            {% for quote in quotes %}
            <ul>
                <li>
                    <a href="{% url 'quoteapp:detail' quote.id %}" role="button" class="outline"> {{ quote.quote }} </a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'quoteapp:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
                    {% endif %}
                </li>
            </ul>
            {% endfor %}

            {% for author in authors %}
            <ul>
                <li>
                    <a href="{% url 'quoteapp:author_detail' author.id %}" role="button" class="outline"> {{ author.fullname }} </a>
                </li>
            </ul>
            {% endfor %}

    </main>
</body>

</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}